import path from 'path'
import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import fs from 'fs'

const manifest = JSON.parse(fs.readFileSync('manifest.json', 'utf8'))

const nodeBuiltins = [...builtins, ...builtins.map((mod) => `node:${mod}`)]

/**
 * Plugin to make pglite's IN_NODE check evaluate to false.
 * pglite checks if it's running in node by evaluating
 * ```ts
 *   typeof process === 'object' &&
 *   typeof process.versions === 'object' &&
 *   typeof process.versions.node === 'string'
 * ```
 * This plugin injects an empty process object at the top of pglite files.
 * 
 * @see https://github.com/electric-sql/pglite/blob/fea963739ccf08ef546265fa3e401bf93f53e81a/packages/pglite/src/utils.ts#L6-L9
 */
const pgliteShimPlugin = {
  name: 'pglite-shim-plugin',
  setup(build) {
    // Handle Windows backslash paths to ensure the pglite shim always takes effect
    build.onLoad({ filter: /@electric-sql[\\/]+pglite/ }, async (args) => {
      const source = await fs.promises.readFile(args.path, 'utf8')
      const shimSource = `const process = {};\n${source}`
      return { contents: shimSource, loader: 'js' }
    })
  },
}

const inlinePgliteWorkerPlugin = {
  name: 'inline-pglite-worker-plugin',
  setup(build) {
    build.onResolve({ filter: /^virtual:pglite-worker-script$/ }, () => ({
      path: 'virtual:pglite-worker-script',
      namespace: 'inline-pglite-worker',
    }))

    build.onLoad(
      {
        filter: /^virtual:pglite-worker-script$/,
        namespace: 'inline-pglite-worker',
      },
      async () => {
        const result = await esbuild.build({
          entryPoints: ['src/database/pglite-worker.ts'],
          bundle: true,
          write: false,
          format: 'iife',
          platform: 'browser',
          target: 'es2020',
          external: [...nodeBuiltins],
          inject: [path.resolve('import-meta-url-shim.js')],
          define: {
            'import.meta.url': 'import_meta_url',
            'process.env.NODE_ENV': JSON.stringify(
              prod ? 'production' : 'development',
            ),
          },
          logLevel: 'silent',
          minify: prod,
          plugins: [pgliteShimPlugin],
        })

        const workerScript = result.outputFiles[0]?.text ?? ''
        return {
          contents: `export default ${JSON.stringify(workerScript)}`,
          loader: 'js',
        }
      },
    )
  },
}

/**
 * Inline pdfjs-dist's worker bundle into main.js as a string. At runtime the
 * string is wrapped in a Blob and handed to pdfjs as `workerSrc`, so pdfjs
 * spawns a real Worker for us. This is intentionally NOT achieved via the
 * pdfjs-shipped `import 'pdfjs-dist/build/pdf.worker.mjs'` pattern, because
 * that import has a side effect (`globalThis.pdfjsWorker = ...`) which
 * collides with Obsidian's built-in PDF viewer when versions differ.
 */
const inlinePdfjsWorkerPlugin = {
  name: 'inline-pdfjs-worker-plugin',
  setup(build) {
    build.onResolve({ filter: /^virtual:pdfjs-worker-script$/ }, () => ({
      path: 'virtual:pdfjs-worker-script',
      namespace: 'inline-pdfjs-worker',
    }))

    build.onLoad(
      {
        filter: /^virtual:pdfjs-worker-script$/,
        namespace: 'inline-pdfjs-worker',
      },
      async () => {
        const workerEntry = path.resolve(
          'node_modules/pdfjs-dist/build/pdf.worker.min.mjs',
        )
        const workerSource = await fs.promises.readFile(workerEntry, 'utf8')
        return {
          contents: `export default ${JSON.stringify(workerSource)}`,
          loader: 'js',
        }
      },
    )
  },
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    '@lexical/clipboard/clipboard',
    ...nodeBuiltins,
  ],
  format: 'cjs',
  inject: [path.resolve('import-meta-url-shim.js')],
  define: {
    'import.meta.url': 'import_meta_url',
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
    '__PLUGIN_BAKED_VERSION__': JSON.stringify(manifest.version),
  },
  target: 'es2020',
  logLevel: 'info', // 'debug' for more detailed output
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  metafile: true,
  loader: {
    '.svg': 'dataurl',
  },
  plugins: [pgliteShimPlugin, inlinePgliteWorkerPlugin, inlinePdfjsWorkerPlugin],
})

if (prod) {
  const result = await context.rebuild()
  fs.writeFileSync('meta.json', JSON.stringify(result.metafile))
  process.exit(0)
} else {
  await context.watch()
}
